library(RSelenium)

m.hit183.8 <- read.csv('./183 (8) Match_Hits.csv', header=TRUE)
m.hit183.8$X <- NULL
m.hit183.8$rRNA <- NULL
m.hit183.8 <- unique(m.hit183.8)

#Removing the mRNAs that were found before:
p.10 <- read.csv('./183.peak.10.csv', header=TRUE)
np.10 <- read.csv('./183.not.peak.10.csv', header=TRUE)
m.hit183.8.rem <- as.data.frame(m.hit183.8[!(m.hit183.8$mRNA %in% p.10$t.183.10.mRNA),])
colnames(m.hit183.8.rem) <- c('mRNA')
m.hit183.8.rem <- as.data.frame(m.hit183.8.rem[!(m.hit183.8.rem$mRNA %in% np.10$mRNA),])
colnames(m.hit183.8.rem) <- c('Locus')
write.csv(m.hit183.8.rem, './m.hit183.8.rem.csv')

#Making the complete 183.8
mr1 <- read.csv('./UTRdb Data Extraction/183.8/UTRdb.183.8.rem COMPLETE.csv', header=TRUE)
mr2 <- read.csv('./UTRdb Data Extraction/183.8/183 UTRdb-Not Peak-(10) COMPLETE.csv', header=TRUE)
mr3 <- read.csv('./UTRdb Data Extraction/183.8/183 UTRdb-Peak-(10).csv', header=TRUE)

m.hit183.8$gene <- mr1$NULL.Gene[match(m.hit183.8$mRNA, mr1$NULL.Locus)]
m1 <- m.hit183.8[complete.cases(m.hit183.8$gene),]
m.hit183.8$gene <- mr2$NULL.Gene[match(m.hit183.8$mRNA, mr2$NULL.Locus)]
m2 <- m.hit183.8[complete.cases(m.hit183.8$gene),]
m.hit183.8$gene <- mr3$NULL.Gene[match(m.hit183.8$mRNA, mr3$NULL.Locus)]
m3 <- m.hit183.8[complete.cases(m.hit183.8$gene),]

UTR.183.8 <- rbind(m1,m2)
UTR.183.8 <- rbind(UTR.183.8,m3)

write.csv(UTR.183.8, './UTRdb Data Extraction/183.8/UTRdb.183(8).complete.csv')

checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 1:1500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 1-1500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 1501:3000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 1501-3000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 3001:4500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 3001-4500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 4501:6000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 4501-6000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 6001:7500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 6001-7500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 7501:9000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 7501-9000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 9001:10500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 9001-10500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 10501:12000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 10501-12000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 12001:13500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 12001-13500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 13501:15000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 13501-15000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 15001:16500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 15001-16500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 16501:18000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 16501-18000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 18001:19500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 18001-19500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 19501:21000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 19501-21000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 21001:22500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 21001-22500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 22501:24000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 22501-24000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 24001:25500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, './UTRdb Data Extraction/183.8/UTRdb.183.8.rem 24001-25500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 25501:27000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 25501-27000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 27001:28500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 27001-28500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 28501:30000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 28501-30000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 30001:31500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 30001-31500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 31501:33000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 31501-33000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 33001:34500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 33001-34500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 34501:36000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 16501-18000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 36001:37500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 36001-37500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 37501:39000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 37501-39000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 39001:40500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 39001-40500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 40501:42000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 40501-42000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 42001:43500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 42001-43500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 43501:45000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 43501-45000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 45001:46500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 45001-46500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 46501:48000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 46501-48000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 48001:49500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 4801-49500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 49501:51000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 49501-51000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 51001:52500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 51001-52500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 52501:54000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 52501-54000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 54001:55500)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 54001-55500.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 55501:57000)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 55501-57000.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################
checkForServer()
startServer()
remDrv <- remoteDriver()
remDrv$open()
C <- data.frame(Gene = character(), Organism = character(), Locus = character(), Region = character(), Length = numeric())
for (i in 57001:58967)
{
  remDrv$navigate('http://utrdb.ba.itb.cnr.it/search')
  remDrv$findElement(using = "xpath", "//select[@id = 'utr_db']/option[@value = '1']")$clickElement()
  remDrv$findElement(using = "xpath", "//input[@id ='ids']")$sendKeysToElement(list(m.hit183.8.rem[i,1], "\uE007"))
  doc <- htmlParse(remDrv$getPageSource()[[1]])
  tab <- readHTMLTable(doc)
  tab <- as.data.frame(tab)
  C <- rbind(C,tab)
  Sys.sleep(1)
}
write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 57001-58967.csv')
remDrv$closeWindow()
remDrv$quit()
remDrv$closeServer()
Sys.sleep(5)
##############################


#-------------------------------------------------------------------------------


C <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 1-1500.csv', header=TRUE)
C$X <- NULL
C1 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 1501-3000.csv', header=TRUE)
C1$X <- NULL
C2 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 3001-4500.csv', header=TRUE)
C2$X <- NULL
C3 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 4501-6000.csv', header=TRUE)
C3$X <- NULL
C4 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 6001-7500.csv', header=TRUE)
C4$X <- NULL
C5 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 7501-9000.csv', header=TRUE)
C5$X <- NULL
C6 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 9001-10500.csv', header=TRUE)
C6$X <- NULL
C7 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 10501-12000.csv', header=TRUE)
C7$X <- NULL
C8 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 12001-13500.csv', header=TRUE)
C8$X <- NULL
C9 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 13501-15000.csv', header=TRUE)
C9$X <- NULL
C10 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 15001-16500.csv', header=TRUE)
C10$X <- NULL
C11 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 16501-18000.csv', header=TRUE)
C11$X <- NULL
C12 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 18001-19500.csv', header=TRUE)
C12$X <- NULL
C13 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 19501-21000.csv', header=TRUE)
C13$X <- NULL
C14 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 21001-22500.csv', header=TRUE)
C14$X <- NULL
C15 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 22501-24000.csv', header=TRUE)
C15$X <- NULL
C16 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 24001-25500.csv', header=TRUE)
C16$X <- NULL
C17 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 25501-27000.csv', header=TRUE)
C17$X <- NULL
C18 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 27001-28500.csv', header=TRUE)
C18$X <- NULL
C19 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 28501-30000.csv', header=TRUE)
C19$X <- NULL
C191 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 30001-31500.csv', header=TRUE)
C191$X <- NULL
C20 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 31501-33000.csv', header=TRUE)
C20$X <- NULL
C21 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 33001-34500.csv', header=TRUE)
C21$X <- NULL
C22 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 34501-36000.csv', header=TRUE)
C22$X <- NULL
C23 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 36001-37500.csv', header=TRUE)
C23$X <- NULL
C24 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 37501-39000.csv', header=TRUE)
C24$X <- NULL
C25 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 39001-40500.csv', header=TRUE)
C25$X <- NULL
C26 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 40501-42000.csv', header=TRUE)
C26$X <- NULL
C27 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 42001-43500.csv', header=TRUE)
C27$X <- NULL
C28 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 43501-45000.csv', header=TRUE)
C28$X <- NULL
C29 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 45001-46500.csv', header=TRUE)
C29$X <- NULL
C30 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 46501-48000.csv', header=TRUE)
C30$X <- NULL
C31 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 48001-49500.csv', header=TRUE)
C31$X <- NULL
C32 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 49501-51000.csv', header=TRUE)
C32$X <- NULL
C33 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 51001-52500.csv', header=TRUE)
C33$X <- NULL
C34 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 52501-54000.csv', header=TRUE)
C34$X <- NULL
C35 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 54001-55500.csv', header=TRUE)
C35$X <- NULL
C36 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 55501-57000.csv', header=TRUE)
C36$X <- NULL
C37 <- read.csv('C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem 57001-58967.csv', header=TRUE)
C37$X <- NULL


C <- rbind(C,C1)
C <- rbind(C,C2)
C <- rbind(C,C3)
C <- rbind(C,C4)
C <- rbind(C,C5)
C <- rbind(C,C6)
C <- rbind(C,C7)
C <- rbind(C,C8)
C <- rbind(C,C9)
C <- rbind(C,C10)
C <- rbind(C,C11)
C <- rbind(C,C12)
C <- rbind(C,C13)
C <- rbind(C,C14)
C <- rbind(C,C15)
C <- rbind(C,C16)
C <- rbind(C,C17)
C <- rbind(C,C18)
C <- rbind(C,C19)
C <- rbind(C,C191)
C <- rbind(C,C20)
C <- rbind(C,C21)
C <- rbind(C,C22)
C <- rbind(C,C23)
C <- rbind(C,C24)
C <- rbind(C,C25)
C <- rbind(C,C26)
C <- rbind(C,C27)
C <- rbind(C,C28)
C <- rbind(C,C29)
C <- rbind(C,C30)
C <- rbind(C,C31)
C <- rbind(C,C32)
C <- rbind(C,C33)
C <- rbind(C,C34)
C <- rbind(C,C35)
C <- rbind(C,C36)
C <- rbind(C,C37)




write.csv(C, 'C:/Users/banijamali.s/Dropbox/Genetics/R/New Results/UTRdb Data Extraction/183.8/UTRdb.183.8.rem COMPLETE.csv')







